# Service for Streamlit UI Application
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: ls1-jan212026
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ls1-jan212026
  name: ls1-jan212026
spec:
  ports:
    - port: 8501
      protocol: TCP
      targetPort: 8501
      name: http
  selector:
    app.kubernetes.io/instance: ls1-jan212026

